// !WARNING!    THIS FILE WAS GENERATED BY GST-PLUGIN-GEN    !WARNING! //
package main

import "C"

import (
	"unsafe"

	"github.com/go-gst/go-gst/gst"
	"github.com/go-gst/go-gst/gst/base"
)

// The metadata for this plugin
var pluginMeta = &gst.PluginMetadata{
	MajorVersion: gst.VersionMajor,
	MinorVersion: gst.VersionMinor,
	Name:         "websink",
	Description:  "WebRTC sink written in Go",
	Version:      "v0.0.1",
	License:      gst.LicenseLGPL,
	Source:       "websink",
	Package:      "websink",
	Origin:       "https://github.com/videologyinc/websink",
	ReleaseDate:  "2025-03-16",
	// The init function is called to register elements provided by the plugin.
	Init: func(plugin *gst.Plugin) bool {
		return gst.RegisterElement(
			plugin,
			// The name of the element
			"websink",
			// The rank of the element
			gst.RankNone,
			// The GoElement implementation for the element
			&WebSink{},
			// The base subclass this element extends
			base.ExtendsBaseSink,
		)
	},
}

// A single method must be exported from the compiled library that provides for GStreamer
// to fetch the description and init function for this plugin. The name of the method
// must match the format gst_plugin_NAME_get_desc, where NAME is the name of the compiled
// artifact with or without the "libgst" prefix and hyphens are replaced with underscores.

//export gst_plugin_websink_get_desc
func gst_plugin_websink_get_desc() unsafe.Pointer { return pluginMeta.Export() }
